# These are supported funding model platforms

github: ['TEAM-BROTHERHOOD-COUNCIL']
community_bridge: EDITH
custom: ['https://t.me/BROTHERHOOD_bots', 'https://t.me/TEAM_BLACK_SUPPORT', 'https://t.me/THE_BROTHERHOOD_COUNCIL']
